// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrdfZMgRzmtVjlB77ZodKwQuGULj1AsEo',
    appId: '1:340451891833:web:8fa77eef386784cc4592a8',
    messagingSenderId: '340451891833',
    projectId: 'flutterqueuenotificationapp',
    authDomain: 'flutterqueuenotificationapp.firebaseapp.com',
    storageBucket: 'flutterqueuenotificationapp.firebasestorage.app',
    databaseURL: 'https://flutterqueuenotificationapp-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAocCmpmmx1-_A6nYxlCBYMYvd0LcE1yNU',
    appId: '1:340451891833:android:6594eb865c84c33a4592a8',
    messagingSenderId: '340451891833',
    projectId: 'flutterqueuenotificationapp',
    storageBucket: 'flutterqueuenotificationapp.firebasestorage.app',
    databaseURL: 'https://flutterqueuenotificationapp-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqZ8T32UZr2OvUgFVcwL62W0cH3FnQl4',
    appId: '1:340451891833:ios:f92d41722d3c7eac4592a8',
    messagingSenderId: '340451891833',
    projectId: 'flutterqueuenotificationapp',
    storageBucket: 'flutterqueuenotificationapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterQueueNotifierApp',
    databaseURL: 'https://flutterqueuenotificationapp-default-rtdb.europe-west1.firebasedatabase.app/',
  );
}
